nacos-host: 127.0.0.1

server:
  port: 4335
spring:
  application:
    name: im-fileServer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
logging:
  config: log4j2-spring.xml
