nacos-host: 1.12.233.249

server:
  port: 4335
spring:
  application:
    name: im-fileServer
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos-host}:8848
logging:
  config: log4j2-spring.xml
