aliyundbhost: rm-wz9i5gw9n7zm8mj4hro.mysql.rds.aliyuncs.com
aliyundbport: 3306
aliyundbusername: im_chat
aliyundbpassword: XuVe1kZCvAGgM5VpZ2+RtjYlnv1GQyo3WGsB737shprmrkNfUL5bjD1ol94odgmvQjjzEEaLqqldWMmJRuULWg==
public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIC63m5n7W98ZCLl3a/92Sia3JXqdr5QAcI3VloRg780u3V3sBU4sXW0gsWqYWha2rzlxV4tprZRpMtbuFYGpoECAwEAAQ==
serverLocalhost: 127.0.0.1 #http://121.196.144.146/
#nacos-host: 1.12.233.249
nacos-host: 119.91.131.147
#nacos-host: 127.0.0.1

server:
  port: 4300

spring:
  application:
    name: im_oauth2-server
  redis:
    host: 127.0.0.1
    database: 1
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos-host}:8848
#        ip: 121.196.144.146
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql属性配置
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-properties: "config.decrypt=true;config.decrypt.key=${public-key}"
      # serverTimezone= Asia/Shanghai 或者 GMT%2B8
      url: jdbc:mysql://${aliyundbhost}:${aliyundbport}/im_chat?useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&allowPublicKeyRetrieval=true
      username: ${aliyundbusername}
      password: ${aliyundbpassword}
      # 使用加密过滤
      filter:
        config:
          enabled: true
      # 初始连接数
      initial-size: 10
      # 最大连接数
      max-active: 50
      filters: stat,wall,slf4j,config

mybatis-plus:
  type-enums-package: com.achobeta.dgut.ab_common

logging:
  config: log4j2-spring.xml

security:
  oauth2:
    client:
      access-token-uri: http://${serverLocalhost}:1225/auth/oauth/token
      user-authorization-uri: http://${serverLocalhost}:1225/auth/oauth/authorize
      client-id: resource
      client-secret: secret
    resource:
      userInfoUri: http://${serverLocalhost}:1225/auth/api/member
      prefer-token-info: false

xcx-appid: wxd2c2de793546cf5d # 小程序id
xcx-secret: 860a17c0e8c4b60181b5093621fdfde6 # 小程序密钥
openId-password: dingdongtxIM #自定义密码
